name: skillbridge

services:

  mysqldb:
    image: mysql:8
    container_name: skillbridge-mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: skillbridge
    ports:
      - "3307:3306"
    volumes:
      - skillbridge_mysql_data:/var/lib/mysql
    networks:
      - skillbridge-network

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: skillbridge-backend
    ports:
      - "2025:8080"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - skillbridge-network

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: skillbridge-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - skillbridge-network

volumes:

  skillbridge_mysql_data:

networks:

  skillbridge-network: